matrix:
    include:
      - script:
            - swift build
            - swift test
        env: JOB=SPM
        os: osx
        osx_image: xcode7.3
        language: objective-c
        install:
            - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)"
notifications:
  email: true